###
PUT http://admin:admin@127.0.0.1:5984/users/ciao
content-type: application/json

{
    "ciao": "ciao"
}


###
GET http://admin:admin@127.0.0.1:5984/cities/_all_docs

###
PUT http://admin:admin@127.0.0.1:5984/cities/parigi
content-type: application/json

{
    "name": "parigi",
    "search": 2
}

###
DELETE http://admin:admin@127.0.0.1:5984/my_database

###
GET http://admin:admin@127.0.0.1:5984/my_database/Q1662313

###
# UPDATE A DOC
POST http://admin:admin@127.0.0.1:5984/cities/_all_docs/queries'

{
    "queries":[
        {
            "keys": ["Roma"]
        },
        {
            "limit":3
        }
    ]
}